on:
  release:
    types:
      - published

name: release

jobs:
  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ">= 3.10"

    - name: deps
      run: python -m pip install -U setuptools build wheel

    - name: build
      run: python -m build

    - name: publish
      uses: pypa/gh-action-pypi-publish@v1.5.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}

    - name: sign
      uses: sigstore/gh-action-sigstore-python@v0.1.0
      with:
        inputs: ./dist/*.tar.gz ./dist/*.whl
        release-signing-artifacts: true
